/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'LowPowerSensorSampling.debug+HP' 
 * Target:  'debug+HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HP.h"

/* AlifSemiconductor::Device:SOC Peripherals:DMA@1.3.0 */
#define RTE_Drivers_DMA 1   /* Driver DMA*/
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:LPTIMER@1.3.0 */
#define RTE_Drivers_LPTIMER   1           /* Driver LPTIMER */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:SPI@1.3.0 */
#define RTE_Drivers_SPI   1           /* Driver SPI */


#endif /* RTE_COMPONENTS_H */
